# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- publish

variables:
  buildConfiguration: 'Debug'

steps:


- script: |
          ~/.dotnet/dotnet publish src/RapidCMS.sln -r "ubuntu.18.04-x64" --self-contained -o $(System.DefaultWorkingDirectory)/linux --configuration $(buildConfiguration)
          rm -r ff $(System.DefaultWorkingDirectory)/linux
          mkdir $(System.DefaultWorkingDirectory)/linux
          cd $(System.DefaultWorkingDirectory)/linux
          zip linux.zip *
          cp $(System.DefaultWorkingDirectory)/linux.zip $(Build.ArtifactStagingDirectory)/linux.zip

  displayName: 'dotnet publish $(buildConfiguration)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'linux.zip'
    publishLocation: 'Container'