# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- publish

variables:
  buildConfiguration: 'Debug'

steps:
- script: |
          mkdir $(System.DefaultWorkingDirectory)/linux
          dotnet publish src/RapidCMS.sln -r "ubuntu.18.04-x64" --self-contained -o $(System.DefaultWorkingDirectory)/linux --configuration $(buildConfiguration)
          cd $(System.DefaultWorkingDirectory)/linux
          zip $(System.DefaultWorkingDirectory)/linux.zip *
          ls -al $(System.DefaultWorkingDirectory)/linux.zip
  displayName: 'dotnet publish $(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Body-And-Brain-Pay-As-You-Go(45098bff-52b9-40b4-b650-a58322e06a0c)'
    appType: 'webAppLinux'
    WebAppName: 'aprilbyrd'
    packageForLinux: '$(System.DefaultWorkingDirectory)/linux.zip'
    RuntimeStack: 'DOTNETCORE|Latest'
    StartupCommand: 'SharpNinja.UI.PersonalCms'
#    ScriptType: 'Inline Script'
#    InlineScript: ':: You can provide your deployment commands here. One command per line.'